name: custom_image_picker
description: Plugin to retrieve all the files from your device.
version: 0.6.0
homepage: https://github.com/TahaMalas/custom_image_picker

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.tahamalas.custom_image_picker
        pluginClass: CustomImagePickerPlugin
      ios:
        pluginClass: CustomImagePickerPlugin
